<?php

declare(strict_types=1);

namespace SymfonyCaptain\Tests;

use PHPUnit\Framework\TestCase;

/**
 * Verifies the distribution bundle generated by `lsp/build.php`: the single
 * self-contained PHP file that is attached to GitHub releases and downloaded by
 * the Zed extension.
 */
final class DistBundleTest extends TestCase
{
    private string $bundlePath = '';

    protected function setUp(): void
    {
        $this->bundlePath = sys_get_temp_dir() . '/symfony-captain-lsp-' . bin2hex(random_bytes(6)) . '.php';
    }

    protected function tearDown(): void
    {
        if ('' !== $this->bundlePath && is_file($this->bundlePath)) {
            unlink($this->bundlePath);
        }
    }

    public function testBuildProducesSyntaxValidPhp(): void
    {
        $this->buildBundle();

        $lint = $this->runPhp(['-l', $this->bundlePath]);
        self::assertSame(0, $lint['exitCode'], $lint['stderr']);
        self::assertStringContainsString('No syntax errors detected', $lint['stdout']);
    }

    public function testBundleIsSelfContained(): void
    {
        $this->buildBundle();

        $bundle = (string) file_get_contents($this->bundlePath);

        self::assertStringStartsWith('#!/usr/bin/env php', $bundle);
        self::assertStringContainsString('final class LspServer', $bundle);
        self::assertStringContainsString('final class RouteProvider', $bundle);
        self::assertStringContainsString('namespace SymfonyCaptain\Lsp;', $bundle);
        self::assertStringContainsString('$server->run(new MessageStream(STDIN, STDOUT));', $bundle);

        foreach (glob(__DIR__ . '/../lsp/src/*.php') as $source) {
            $declaration = preg_quote(basename($source, '.php'), '/');

            self::assertMatchesRegularExpression('/\b(?:final class|interface) ' . $declaration . '\b/', $bundle);
        }
    }

    public function testBundleRespondsToInitializeOverStdin(): void
    {
        $this->buildBundle();

        $initialize = json_encode([
            'jsonrpc' => '2.0',
            'id' => 1,
            'method' => 'initialize',
            'params' => ['processId' => 123, 'rootPath' => __DIR__ . '/Fixture/Project'],
        ]);
        $shutdown = json_encode(['jsonrpc' => '2.0', 'id' => 2, 'method' => 'shutdown']);
        $exit = json_encode(['jsonrpc' => '2.0', 'method' => 'exit']);

        $result = $this->runLspSubprocess([$initialize, $shutdown, $exit]);
        self::assertSame(0, $result['exitCode'], $result['stderr']);

        $messages = $this->parseMessages($result['stdout']);
        self::assertCount(2, $messages);

        $response = $messages[0];
        self::assertSame(1, $response['id']);
        self::assertArrayHasKey('capabilities', $response['result']);
        self::assertTrue($response['result']['capabilities']['workspaceSymbolProvider']);
        self::assertSame(null, $messages[1]['result']);
    }

    private function buildBundle(): void
    {
        $result = $this->runPhp([__DIR__ . '/../lsp/build.php', $this->bundlePath]);
        self::assertSame(0, $result['exitCode'], $result['stderr'] . $result['stdout']);
        self::assertFileExists($this->bundlePath);
    }

    /**
     * @param list<string> $arguments
     *
     * @return array{stdout: string, stderr: string, exitCode: int}
     */
    private function runPhp(array $arguments): array
    {
        $command = array_merge([PHP_BINARY], $arguments);
        $process = proc_open($command, [
            1 => ['pipe', 'w'],
            2 => ['pipe', 'w'],
        ], $pipes);

        self::assertIsResource($process);

        $stdout = stream_get_contents($pipes[1]);
        $stderr = stream_get_contents($pipes[2]);
        fclose($pipes[1]);
        fclose($pipes[2]);

        return [
            'stdout' => (string) $stdout,
            'stderr' => (string) $stderr,
            'exitCode' => proc_close($process),
        ];
    }

    /**
     * @param list<string> $messages
     *
     * @return array{stdout: string, stderr: string, exitCode: int}
     */
    private function runLspSubprocess(array $messages): array
    {
        $process = proc_open([PHP_BINARY, $this->bundlePath], [
            0 => ['pipe', 'r'],
            1 => ['pipe', 'w'],
            2 => ['pipe', 'w'],
        ], $pipes);

        self::assertIsResource($process);

        foreach ($messages as $message) {
            fwrite($pipes[0], sprintf("Content-Length: %d\r\n\r\n%s", strlen($message), $message));
        }

        fclose($pipes[0]);
        $stdout = stream_get_contents($pipes[1]);
        $stderr = stream_get_contents($pipes[2]);
        fclose($pipes[1]);
        fclose($pipes[2]);

        return [
            'stdout' => (string) $stdout,
            'stderr' => (string) $stderr,
            'exitCode' => proc_close($process),
        ];
    }

    /**
     * @return list<array<string, mixed>>
     */
    private function parseMessages(string $raw): array
    {
        $messages = [];
        $offset = 0;

        while ($offset < strlen($raw)) {
            $headersEnd = strpos($raw, "\r\n\r\n", $offset);

            if (false === $headersEnd) {
                break;
            }

            $headers = substr($raw, $offset, $headersEnd - $offset);

            if (!preg_match('/Content-Length:\s*(\d+)/i', $headers, $matches)) {
                break;
            }

            $length = (int) $matches[1];
            $bodyStart = $headersEnd + 4;
            $messages[] = json_decode(substr($raw, $bodyStart, $length), true, 512, JSON_THROW_ON_ERROR);
            $offset = $bodyStart + $length;
        }

        return $messages;
    }
}
