#!/usr/bin/env php
<?php

declare(strict_types=1);

/**
 * Concatenates the SymfonyCaptain\Lsp classes into a single self-contained PHP
 * file that can be attached to a GitHub release and downloaded by the Zed
 * extension. The generated bundle does not depend on this repository's
 * composer autoloader.
 *
 * Usage: php lsp/build.php [output-path]
 */

$srcDir = __DIR__ . '/src';
$outputPath = $argv[1] ?? dirname(__DIR__) . '/dist/symfony-captain-lsp.php';

$files = glob($srcDir . '/*.php');

if (false === $files) {
    fwrite(STDERR, sprintf('Cannot list PHP sources in "%s".', $srcDir) . PHP_EOL);
    exit(1);
}

sort($files);

$bundle = "#!/usr/bin/env php\n";
$bundle .= "<?php\n\n";
$bundle .= "declare(strict_types=1);\n\n";
$bundle .= "/**\n";
$bundle .= " * Symfony Captain language server — distribution bundle.\n";
$bundle .= " * Generated by lsp/build.php — do not edit directly.\n";
$bundle .= " */\n";

foreach ($files as $file) {
    $source = (string) file_get_contents($file);
    $namespacePosition = strpos($source, 'namespace SymfonyCaptain\\Lsp;');

    if (false === $namespacePosition) {
        fwrite(STDERR, sprintf('Cannot find namespace declaration in "%s".', $file) . PHP_EOL);
        exit(1);
    }

    $bundle .= "\n// Source: " . basename($file) . "\n";
    $bundle .= substr($source, $namespacePosition);
}

$bundle .= "\nnamespace SymfonyCaptain\\Lsp;\n\n";
$bundle .= '$server = new LspServer();' . PHP_EOL;
$bundle .= '$server->run(new MessageStream(STDIN, STDOUT));' . PHP_EOL;

$outputDirectory = dirname($outputPath);

if (!is_dir($outputDirectory) && !mkdir($outputDirectory, 0777, true) && !is_dir($outputDirectory)) {
    fwrite(STDERR, sprintf('Cannot create output directory "%s".', $outputDirectory) . PHP_EOL);
    exit(1);
}

if (false === file_put_contents($outputPath, $bundle)) {
    fwrite(STDERR, sprintf('Cannot write bundle to "%s".', $outputPath) . PHP_EOL);
    exit(1);
}

fwrite(STDOUT, sprintf('Wrote %s (%d bytes).', $outputPath, filesize($outputPath)) . PHP_EOL);
